name: 'Create-Tinycheck-IOC-File'
on:
  push:
    branches: ['master']
    paths: ['network.csv']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Build IOC File
      run: |
          pip install -r requirements.txt
          python create-indicators-for-tinycheck.py
    - name: Commit files  # transfer the json file in the repo
      run: |
        git config --local user.name  ${{ github.actor }}
        git add indicators-for-tinycheck.json
        git commit -m "Updating indicators-for-tinycheck.json"
    - name: Push changes  # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
